Support macos-14 and newer ARM64 machines on CI

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -182,8 +182,123 @@ jobs:
           fail_ci_if_error: true # optional (default = false)
           verbose: true
 
-  macOS:
+  macOS-x86_64: # Remove when the Intel runners on CI no longer exist
     runs-on: macos-13 # Update Xcode version to the latest available as well
+    strategy:
+      fail-fast: false
+      matrix:
+        build-type:
+          [
+            "",
+            "--enable-debug --disable-optimize",
+            "--enable-debug --disable-optimize --enable-simulator=arm64",
+            "--enable-address-sanitizer",
+          ]
+        python-version: ["3.10"]
+    steps:
+      - name: Set Xcode version
+        shell: bash
+        run: |
+          sudo xcode-select -s "/Applications/Xcode_15.1.app"
+          echo "MD_APPLE_SDK_ROOT=/Applications/Xcode_15.1.app" >> $GITHUB_ENV
+      - uses: actions/checkout@v3
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Get pip cache dir
+        id: pip-cache
+        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
+      - name: pip cache
+        uses: actions/cache@v3
+        with:
+          path: ${{ steps.pip-cache.outputs.dir }}
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
+          restore-keys: ${{ runner.os }}-pip-
+      - name: Use deploy key
+        uses: webfactory/ssh-agent@v0.7.0
+        with:
+          ssh-private-key: |
+            ${{ secrets.CRASH2COV_TOKEN }}
+            ${{ secrets.ZZBASE_TOKEN }}
+
+      - name: Install pip prerequisites
+        if: steps.pip-cache.outputs.cache-hit != 'true'
+        run: python -u -m pip install --upgrade pip setuptools wheel ;
+      - name: Removing subdomain to make requirements.txt setup work in CI
+        run: python -c 'import fileinput; [print(line.partition("git@")[0] + "git@github.com/" + line.partition(".github.com/")[-1] if (".github.com/" in line and not line.startswith("#")) else line, end="") for line in fileinput.input(inplace=True)]' requirements.txt ; git diff ;
+      - name: Install requirements from possibly-changed requirements.txt
+        if: steps.pip-cache.outputs.cache-hit != 'true'
+        run: pip install -r requirements.txt ;
+      - name: Revert requirements.txt if changed
+        if: steps.pip-cache.outputs.cache-hit != 'true'
+        run: git checkout -- requirements.txt ;
+      - name: Install package in development mode
+        if: steps.pip-cache.outputs.cache-hit != 'true'
+        run: pip install --upgrade -e . ;
+
+      - name: Run with ruff
+        run: python -u -m ruff .
+      - name: Run with vulture to find dead code
+        if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
+        run: |
+          python -c 'exec("from pathlib import Path;import shutil;import subprocess;\ntry: import tomllib;\nexcept ImportError: import tomli as tomllib;\nwith Path(\"pyproject.toml\").open(mode=\"rb\") as fp: c = tomllib.load(fp); n = c[\"project\"][\"name\"];\nif not (v := shutil.which(\"vulture\")): raise RuntimeError(\"Please first install vulture\");\nfor z in sorted({x.split(\"  # \",maxsplit=1)[0] for x in sorted(subprocess.run([y for y in [v,\".\",\".vulture_allowlist\" if Path(\".vulture_allowlist\").is_file() else \"\"] if y],capture_output=True,text=True).stdout.rstrip().splitlines()) if not x.startswith(\"# \")}): print(z)")'
+
+      - name: Make sure LLVM is installed and look for available LLVM versions
+        run: brew install llvm || true ; brew link --overwrite python@3.11 ; brew install llvm ; ls -l /usr/local/Cellar/llvm/
+      - name: Set macOS environment variables
+        run: |
+          echo "LLVM_CONFIG=/usr/local/Cellar/llvm/$(pushd /usr/local/Cellar/llvm/ > /dev/null ; ls -d */ | sed 's/.$//' ; popd > /dev/null;)/bin/llvm-config" >> $GITHUB_ENV ;
+          echo "LLVM_SYMBOLIZER=/usr/local/Cellar/llvm/$(pushd /usr/local/Cellar/llvm/ > /dev/null ; ls -d */ | sed 's/.$//' ; popd > /dev/null;)/bin/llvm-symbolizer" >> $GITHUB_ENV ;
+      - name: Set macOS llvm-config and llvm-symbolizer symlinks
+        run: |
+          sudo ln -s /usr/local/Cellar/llvm/"$(pushd /usr/local/Cellar/llvm/ > /dev/null ; ls -d */ | sed 's/.$//' ; popd > /dev/null;)"/bin/llvm-config /usr/local/bin/llvm-config ;
+          sudo ln -s /usr/local/Cellar/llvm/"$(pushd /usr/local/Cellar/llvm/ > /dev/null ; ls -d */ | sed 's/.$//' ; popd > /dev/null;)"/bin/llvm-symbolizer /usr/local/bin/llvm-symbolizer ;
+      - name: Check versions
+        run: gcc --version; g++ --version; clang --version; clang++ --version; llvm-symbolizer --version; llvm-config --version
+      - name: Install 32/64-bit SpiderMonkey prerequisites and forcibly overwrite existing brew issues when linking Python
+        run: brew install autoconf@2.13 ccache gawk gnu-tar mercurial pkg-config python ripgrep zlib || true ; brew link --overwrite python@3.11 ; brew autoremove
+      - name: Rustup latest 32/64-bit Rust, as it seems faster than Rust-related workflows
+        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path && source "$HOME"/.cargo/env && rustup target add i686-unknown-linux-gnu
+
+      - name: Clone Mercurial mozilla-central repo as a stream, retrying in times of failure
+        run: |
+          mkdir -p "$HOME"/trees && hg --version -q ;
+          until time hg clone --stream https://hg.mozilla.org/mozilla-central/ "$HOME"/trees/mozilla-central/ ; do
+            echo "Error cloning m-c. Deleting its failed clone directory, then retrying in 2 seconds..." ;
+            rm -rf "$HOME"/trees/mozilla-central/ ;
+            sleep 2 ;
+          done
+
+      - name: Run tools using pytest under code coverage
+        env:
+          BUILDSM: ${{ matrix.build-type }}
+        run: |
+          python -u -m pytest --cov --mypy --pylint --ruff --ruff-format
+
+      - name: Print the .busted log, if any, when any previous compile steps fail
+        if: ${{ failure() }}
+        run: tail -n 100 "$HOME"/shell-cache/*/*.busted*
+
+      - name: Remove m-c to free up more space for tarball creation
+        run: rm -rf "$HOME"/trees/mozilla-central/
+      - name: Create a tarball and SHA-256 checksum
+        run: pushd "$HOME"/shell-cache; for f in *; do [[ $f =~ "js-" ]] && time gtar -cpf - "$f" | zstd -T0 --long -19 > "$f".tar.zst && shasum -a 256 -b "$f".tar.zst | tee "$f".tar.zst.sha256; done; popd
+      - name: Archive tarball and checksum # GitHub UI forces download as zipped (not gzipped) files, double-compressing even if files are already compressed
+        uses: nth10sd/upload-artifact-as-is@v0
+        with:
+          path: "~/shell-cache/*.tar.zst*"
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v3
+        continue-on-error: true # codecov limits number of uploads allowed for each commit
+        with:
+          # token: ${{ secrets.CODECOV_TOKEN }}
+          env_vars: OS,PYTHON
+          fail_ci_if_error: true # optional (default = false)
+          verbose: true
+
+  macOS-arm64:
+    runs-on: macos-14 # Update Xcode version to the latest available as well
     strategy:
       fail-fast: false
       matrix:
